# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0abb649b83ce37646dbd1ed98f7fafef3bde3ed2889e280cf6470e018af242ea866767efa5af2927939270724596d2fc19af82a8e09f2e2325d71c749af06698

test:
  secret_key_base: 9e66468392182b80f4b336c82d0ddf532c299ed401bce2d7664047ce4ee094ad4de89aa495d6f8bca336308af318463e846359e0d1b04593b822e713eb0dbb1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
